server:
  port: 8080

spring:
  application:
    name: database-learning-api
  datasource:
    url: jdbc:postgresql://localhost:5432/empresa_db
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
