apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: academia
type: Opaque
data:
  # echo -n "postgres123" | base64
  postgres-password: cG9zdGdyZXMxMjM=
  # echo -n "jwtSecretKey2026" | base64
  jwt-secret: and0U2VjcmV0S2V5MjAyNg==
